### ISSUE TITLE
Make a new Typeform, independent from The CS

### ISSUE THREAD

**Issue by JuankBell** [CommonsBuild/Gravity#1]
The CS has a lot of sensible information, as well as Gravity. we need to handle that information in separate ways :)

**Comment by csggene3** [comment]
Hi @JuankBell Do you mean "sensitive" information? As in private information that requires competent discretion as well as functional information security? I'm sure I could whip up a Typeform that would meet those criteria in an afternoon, or we could do it together during a 30-60 min call or something, if that would be desirable. And particularly considering this has been waiting since September, if you just want this completed, or don't have the bandwidth, I'd be happy to prioritize this to help clear it from the board for you. = )
